// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvtGoMDbI79tBKth42BouiXvuCFJbSmRA',
    appId: '1:667936759100:web:d440f8d391d6c050de9239',
    messagingSenderId: '667936759100',
    projectId: 'connective-5d44e',
    authDomain: 'connective-5d44e.firebaseapp.com',
    storageBucket: 'connective-5d44e.firebasestorage.app',
    measurementId: 'G-B7V52RLT5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp2RxEHvS7kB_cRNIx4t1oC4VFQPDqWvo',
    appId: '1:667936759100:android:6667eac6ec7aa827de9239',
    messagingSenderId: '667936759100',
    projectId: 'connective-5d44e',
    storageBucket: 'connective-5d44e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlO3dYaxTYPl5OVpNiwy8xtGByhvosopk',
    appId: '1:667936759100:ios:d82029568d47eea2de9239',
    messagingSenderId: '667936759100',
    projectId: 'connective-5d44e',
    storageBucket: 'connective-5d44e.firebasestorage.app',
    iosBundleId: 'com.example.connective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlO3dYaxTYPl5OVpNiwy8xtGByhvosopk',
    appId: '1:667936759100:ios:d82029568d47eea2de9239',
    messagingSenderId: '667936759100',
    projectId: 'connective-5d44e',
    storageBucket: 'connective-5d44e.firebasestorage.app',
    iosBundleId: 'com.example.connective',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvtGoMDbI79tBKth42BouiXvuCFJbSmRA',
    appId: '1:667936759100:web:807ea33955c23ab6de9239',
    messagingSenderId: '667936759100',
    projectId: 'connective-5d44e',
    authDomain: 'connective-5d44e.firebaseapp.com',
    storageBucket: 'connective-5d44e.firebasestorage.app',
    measurementId: 'G-DWTDCF9T07',
  );
}
